---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/sessions":
    post:
      summary: create session
      responses:
        '200':
          description: successful
  "/api/sessions/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show session
      responses:
        '200':
          description: successful
    delete:
      summary: delete session
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
